### PR TITLE
Check access before chmod

### PR DESCRIPTION
**Pull request by ubaumann**
Quick fix. Checking if chmod is needed

### CODE REVIEW

**Comment by zwiy** [comment]
I'd like to have this feature too 👍.

**Comment by ubaumann** [comment]
Hi @seboschtion 
We could test the fix and it is working well so far. Are you still interested in maintaining this project? Otherwise I could move it to INSRapperswil if you give me the permissions. Also it would be great if you could add me (https://pypi.org/user/ubaumann/) on pypi so I can release.

Thanks, Urs

**Comment by seboschtion** [comment]
Hani nöd gseh, danke für de Commit!

**Comment by ubaumann** [comment]
Danke dir!!

**Comment by seboschtion** [comment]
Danke dir! Jetzt au uf pypi

**Comment by ubaumann** [comment]
Perfekt 😍

**Pull request merged**
